/* global it, cy, describe */
describe('Basic My-Learning-Analytics Testing', function () {
  it('logging in with correct credentials shows courses', function () {
    cy.visit('/')
    cy.get('#id_username')
      .type('donald07')
      .should('have.value', 'donald07')
    cy.get('#id_password')
      .type('root')
    cy.get('button[type="submit"]')
      .click()
    cy.contains('EECS 808 008 FA 2057')
      .click()
    cy.url().should('include', '/courses/')
    cy.visit('/accounts/logout')
    cy.url().should('include', '/login')
  })

  it('logging in with incorrect credentials shows error', function () {
    cy.visit('/')
    cy.get('#id_username')
      .type('donald08')
      .should('have.value', 'donald08')
    cy.get('#id_password')
      .type('root')
    cy.get('button[type="submit"]')
      .click()
    cy.contains('EECS 808 008 FA 2057').should('not.exist')
    cy.url().should('not.include', '/courses/')
    cy.contains('Please enter a correct username and password. Note that both fields may be case-sensitive.')
    cy.url().should('include', '/login')
  })

  it('Grade for donald07 is 70% and chart matches', function () {
    cy.visit('/')
    cy.get('#id_username')
      .type('donald07')
      .should('have.value', 'donald07')
    cy.get('#id_password')
      .type('root')
    cy.get('button[type="submit"]')
      .click()
    cy.contains('EECS 808 008 FA 2057')
      .click()
    cy.get('div[title="Grade Distribution"]')
      .click()
    cy.get('input[type="checkbox"]').check()
    cy.contains('td', 'My grade').parent().children('td').children('strong').as('my_grade').should('contain', '70%')
    cy.get('rect').parent().parent().toMatchSnapshot()
    cy.get('input[type="checkbox"]').uncheck()
    cy.get('my_grade').should('not.exist')
    cy.get('rect').parent().parent().toMatchSnapshot()
    cy.get('input[type="checkbox"]').check()
    cy.visit('/accounts/logout')
  })

  it('donald07 is 100% complete with their assignments.', function () {
    cy.visit('/')
    cy.get('#id_username')
      .type('donald07')
      .should('have.value', 'donald07')
    cy.get('#id_password')
      .type('root')
    cy.get('button[type="submit"]')
      .click()
    cy.contains('EECS 808 008 FA 2057')
      .click()
    cy.get('a[href="/courses/362855/assignments"]').children('div').children('button')
      .click()
    cy.contains('Clear')
      .click()
    cy.get('#standard-number')
      .type('100')
    cy.contains('Goal: 100%').parent().parent().toMatchSnapshot()
    cy.contains('Clear')
      .click()
    cy.visit('/accounts/logout')
  })

  it('donald07 is a user of many resources', function () {
    cy.visit('/')
    cy.get('#id_username')
      .type('donald07')
      .should('have.value', 'donald07')
    cy.get('#id_password')
      .type('root')
    cy.get('button[type="submit"]')
      .click()
    cy.contains('EECS 808 008 FA 2057')
      .click()
    cy.contains('Resources Accessed')
      .click()
    cy.get('.rc-slider').toMatchSnapshot()
    cy.get('.rc-slider-step').children('.rc-slider-dot').first().next()
      .click()
    cy.get('.rc-slider').toMatchSnapshot()
    cy.get('.rc-slider-step').children('.rc-slider-dot').first()
      .click()
    cy.wait(1000) // should delay the testing long enough for svg to update
    cy.get('.svgWrapper').toMatchSnapshot()
    cy.contains('All')
      .click()
    cy.get('li[data-value="70-79"]')
      .click()
    cy.wait(1000) // should delay the testing long enough for svg to update
    cy.get('.svgWrapper').toMatchSnapshot()
    cy.contains('70-79%')
      .click()
    cy.get('li[data-value="All"]')
      .click()
    cy.visit('/accounts/logout')
  })
})
