# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.TextField(default='', verbose_name='File Type'),
            preserve_default=False,
        ),
    ]
