# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190613_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterms',
            name='canvas_id',
            field=models.BigIntegerField(verbose_name='Canvas Id'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_group_id',
            field=models.BigIntegerField(verbose_name='Assignment Group Id'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.BigIntegerField(verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Assignment Id'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.FloatField(blank=True, null=True, verbose_name='Points Possible'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='course_id',
            field=models.BigIntegerField(verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='drop_highest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Drop Highest'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='drop_lowest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Drop Lowest'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='group_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Group Points'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Assignment Group Id'),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='assignmentweightconsideration',
            name='course_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='canvas_id',
            field=models.BigIntegerField(db_column='canvas_id', verbose_name='Canvas Course Id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigIntegerField(db_column='id', editable=False, primary_key=True, serialize=False, verbose_name='Unizin Course Id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course_id',
            field=models.BigIntegerField(verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='File Id'),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='file_id',
            field=models.BigIntegerField(blank=True, verbose_name='File Id'),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='user_id',
            field=models.BigIntegerField(blank=True, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_id',
            field=models.BigIntegerField(verbose_name='Assignment Id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_id',
            field=models.BigIntegerField(verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Submission Id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='final_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Final Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='userdefaultselection',
            name='course_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Course Id'),
        ),
        migrations.AlterField(
            model_name='userdefaultselection',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User Id'),
        ),
    ]
