# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190613_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseviewoption',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Course', verbose_name='Course View Option Id'),
        ),
    ]
