# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190613_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefaultselection',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Id'),
        ),
    ]
