# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190626_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdefaultselection',
            old_name='user_id',
            new_name='user_sis_name',
        ),
        migrations.AlterUniqueTogether(
            name='userdefaultselection',
            unique_together=set([('user_sis_name', 'course_id', 'default_view_type')]),
        ),
    ]
