# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190626_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource_type',
            field=models.TextField(default='', verbose_name='Resource Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='File Id'),
        ),
        migrations.AlterField(
            model_name='fileaccess',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='File Id'),
        ),
    ]
