# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190626_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource_type',
            field=models.TextField(default='', verbose_name='Resource Type'),
            preserve_default=False,
        ),
    ]
