# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190715_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=255, verbose_name='Resource Type'),
        ),
    ]
