# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190731_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term_id',
        ),
        migrations.AddField(
            model_name='course',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time'),
        ),
        migrations.AddField(
            model_name='course',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date and Time'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(db_column='term_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.AcademicTerms', verbose_name='Term Id'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Term End Date and Time'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Term Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='Unizin Course Id'),
        ),
    ]
