# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190812_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ab_test_course',
            field=models.BooleanField(default=False, verbose_name='AB test course (For showing grades count on bars)'),
        ),
    ]
