# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190812_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefaultselection',
            name='default_view_value',
            field=models.TextField(blank=True, null=True, verbose_name='Default Value'),
        ),
    ]
