# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190812_0924'),
        ('dashboard', '0010_auto_20190807_1547'),
    ]

    operations = [
    ]
