# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190812_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDateRange',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='date_range', serialize=False, to='dashboard.Course')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Start Date and Time')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time')),
                ('managedByAdmin', models.BooleanField(default=False, verbose_name='Range Managed by Administrator')),
            ],
            options={
                'verbose_name': 'Course Date Range',
                'db_table': 'course_date_range',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_start',
        ),
    ]
