# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190812_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_grade_counts',
            field=models.BooleanField(default=False, verbose_name='Show Grade Counts'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigIntegerField(db_column='id', editable=False, primary_key=True, serialize=False, verbose_name='Course Id'),
        ),
    ]
