# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190920_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade_posted_local_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posted Grade in local DateTime'),
        ),
    ]
