# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_coursetemp_courseviewoptiontemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='courseviewoption',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseViewOption',
        ),
    ]
