# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_submission_grade_posted_local_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_grade_type',
            field=models.CharField(choices=[('Percent', 'Percent'), ('Point', 'Point')], default='Percent', max_length=255, verbose_name='Show Grade Type'),
        ),
    ]
