# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_course_show_grade_type'),
        ('dashboard', '0011_auto_20190924_1501'),
    ]

    operations = [
    ]
