# Generated by Django 2.2.9 on 2020-01-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190924_1501'),
        ('dashboard', '0013_course_show_grade_type'),
    ]

    operations = [
    ]
