# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20200114_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseviewoption',
            name='show_assignment_planning_v1',
            field=models.BooleanField(default=True, verbose_name='Show Assignment Planning v1 View'),
        ),
    ]
