# Generated by Django 2.2.9 on 2020-01-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_auto_field_to_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseviewoption',
            name='show_assignment_planning_v1',
            field=models.BooleanField(default=True, verbose_name='Show Assignment Planning v1 View'),
        ),
        migrations.AlterField(
            model_name='userdefaultselection',
            name='default_view_value',
            field=models.TextField(blank=True, null=True, verbose_name='Default Value'),
        ),
    ]
