# Generated by Django 2.2.10 on 2020-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200116_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('resource_type', models.CharField(max_length=255, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, max_length=255, verbose_name='Resource Id')),
                ('name', models.TextField(verbose_name='Resource Name')),
                ('course_id', models.BigIntegerField(verbose_name='Course Id')),
            ],
            options={
                'db_table': 'resource1',
            },
        ),
    ]
