# Generated by Django 2.2.14 on 2020-07-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200116_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course_id',
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        # Need to run this manual SQL to clean up the duplicates before making field unique
        migrations.RunSQL("""
            DELETE r1 FROM resource r1 INNER JOIN resource r2 WHERE 
            r1.id < r2.id AND r1.resource_id = r2.resource_id;
            """
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Resource Id'),
        ),
        # Clean up old rows before adding the foreign key
        migrations.RunSQL("""
            DELETE FROM resource_access WHERE resource_id NOT IN (SELECT resource_id FROM resource);
            """
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource_id',
            field=models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Resource', to_field='resource_id'),
        ),
    ]
