# Generated by Django 2.2.10 on 2020-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_resource1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource1',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resource Id'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id'),
        ),
    ]
