# Generated by Django 2.2.14 on 2020-07-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200116_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('resource_id', 'course_id')},
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='Resource Id'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource_id',
            field=models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Resource', to_field='resource_id'),
        ),
    ]
