# Generated by Django 2.2.14 on 2020-07-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_utf8_conversion'),
    ]

    operations = [
        # We have to remove all rows from resource and resource access before performing this migration
        # As there is no way of knowing which course_id a resource access was linked to
        # This is the current process for the cron anyway
        migrations.RunSQL("DELETE FROM resource_access;"),
        migrations.RunSQL("DELETE FROM resource;"),
        migrations.RemoveField(
            model_name='resource',
            name='course_id',
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Resource Id'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource_id',
            field=models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Resource', to_field='resource_id'),
        ),
    ]
