# Generated by Django 3.0.8 on 2020-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_adding_mysql_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_cron_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time cron ran for this course'),
        ),
    ]
