# Generated by Django 3.2.15 on 2022-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_user_sis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='data_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data last updated'),
        ),
    ]
