# Generated by Django 3.2.15 on 2022-09-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_course_data_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
