# Generated by Django 3.2.19 on 2023-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseviewoption',
            name='show_assignment_planning_v1',
        ),
    ]
