# Generated by Django 3.2.20 on 2023-09-06 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_courseviewoption_show_assignment_planning_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date'),
        ),
    ]
