# Generated by Django 3.2.20 on 2023-12-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_course_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='local_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='grade_posted_local_date',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade_posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posted Grade DateTime'),
        ),
    ]
