# Generated by Django 3.2.20 on 2023-12-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_or_change_local_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Time zone'),
        ),
    ]
