# Generated by Django 4.2.11 on 2024-07-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_or_change_local_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterms',
            name='canvas_id',
            field=models.BigIntegerField(verbose_name='Academic Term Canvas Id'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', null=True, verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='date_start',
            field=models.DateTimeField(blank=True, help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', null=True, verbose_name='Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Academic Term Id'),
        ),
        migrations.AlterField(
            model_name='academicterms',
            name='name',
            field=models.CharField(help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignmentgroups',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='data_last_updated',
            field=models.DateTimeField(blank=True, help_text='This is the last time the cron was run and can be reset on the main courses page with the dropdown', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', null=True, verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateTimeField(blank=True, help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', null=True, verbose_name='Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='This field will be automatically populated by cron to match Canvas but can be adjusted if desired', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.ForeignKey(db_column='term_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.academicterms'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
