# Generated by Django 4.2.14 on 2024-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_or_change_local_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_accessed_date',
            field=models.DateTimeField(blank=True, help_text='The last time this course was accessed', null=True),
        ),
    ]
