# Generated by Django 4.2.11 on 2024-05-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_or_change_local_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
