# Generated by Django 4.2.11 on 2024-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_or_change_local_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_index=True, verbose_name='User Id'),
        ),
    ]
