# Generated by Django 4.2.11 on 2024-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_academicterms_canvas_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['user_id'], name='user_id_idx'),
        ),
    ]
