# Generated by Django 4.2.18 on 2025-02-24 18:47

from django.db import migrations
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_course_last_accessed_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE course
                JOIN (
                    SELECT 
                        CAST(JSON_UNQUOTE(JSON_EXTRACT(extra, '$.course_id')) AS UNSIGNED) - {increment_value} AS course_id,
                        MAX(timestamp) AS last_accessed_date
                    FROM eventlog_log
                    WHERE JSON_CONTAINS_PATH(extra, 'one', '$.course_id')
                    GROUP BY course_id
                ) AS subquery
                ON course.canvas_id = subquery.course_id
                SET course.last_accessed_date  = subquery.last_accessed_date;
            """.format(increment_value=settings.CANVAS_DATA_ID_INCREMENT),
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[],
            hints={'atomic': False},
        ),
    ]
